import './globals.css'
import type { Metadata } from "next";
import { ErrorBoundary } from "@/components/ErrorBoundary";

import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from 'next/font/google';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <ClerkProvider>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
